package orm;
// Generated 06-ene-2018 11:57:57 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Comic generated by hbm2java
 */
public class Comic implements java.io.Serializable {

	private int idComic;
	private String nombre;
	private Integer isbn;
	private byte[] foto;
	private String anotacionPrivada;
	private Set<ComicHasSerie> comicHasSeries = new HashSet<ComicHasSerie>(0);
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);

	public Comic() {
	}

	public Comic(int idComic, String nombre) {
		this.idComic = idComic;
		this.nombre = nombre;
	}

	public Comic(int idComic, String nombre, Integer isbn, byte[] foto, String anotacionPrivada, Set<ComicHasSerie> comicHasSeries,
			Set<Publicacion> publicacions) {
		this.idComic = idComic;
		this.nombre = nombre;
		this.isbn = isbn;
		this.foto = foto;
		this.anotacionPrivada = anotacionPrivada;
		this.comicHasSeries = comicHasSeries;
		this.publicacions = publicacions;
	}

	public int getIdComic() {
		return this.idComic;
	}

	public void setIdComic(int idComic) {
		this.idComic = idComic;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIsbn() {
		return this.isbn;
	}

	public void setIsbn(Integer isbn) {
		this.isbn = isbn;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getAnotacionPrivada() {
		return this.anotacionPrivada;
	}

	public void setAnotacionPrivada(String anotacionPrivada) {
		this.anotacionPrivada = anotacionPrivada;
	}

	public Set<ComicHasSerie> getComicHasSeries() {
		return this.comicHasSeries;
	}

	public void setComicHasSeries(Set<ComicHasSerie> comicHasSeries) {
		this.comicHasSeries = comicHasSeries;
	}

	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

}
