package orm;
// Generated 06-ene-2018 11:57:57 by Hibernate Tools 5.2.3.Final

/**
 * ComicHasSerie generated by hbm2java
 */
public class ComicHasSerie implements java.io.Serializable {

	private ComicHasSerieId id;
	private Comic comic;
	private Serie serie;
	private String anotacionPublica;

	public ComicHasSerie() {
	}

	public ComicHasSerie(ComicHasSerieId id, Comic comic, Serie serie) {
		this.id = id;
		this.comic = comic;
		this.serie = serie;
	}

	public ComicHasSerie(ComicHasSerieId id, Comic comic, Serie serie, String anotacionPublica) {
		this.id = id;
		this.comic = comic;
		this.serie = serie;
		this.anotacionPublica = anotacionPublica;
	}

	public ComicHasSerieId getId() {
		return this.id;
	}

	public void setId(ComicHasSerieId id) {
		this.id = id;
	}

	public Comic getComic() {
		return this.comic;
	}

	public void setComic(Comic comic) {
		this.comic = comic;
	}

	public Serie getSerie() {
		return this.serie;
	}

	public void setSerie(Serie serie) {
		this.serie = serie;
	}

	public String getAnotacionPublica() {
		return this.anotacionPublica;
	}

	public void setAnotacionPublica(String anotacionPublica) {
		this.anotacionPublica = anotacionPublica;
	}

}
