package orm;
// Generated 02-dic-2017 22:16:46 by Hibernate Tools 5.2.3.Final

/**
 * ComicId generated by hbm2java
 */
public class ComicId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idComic;
	private int serieIdserie;

	public ComicId() {
	}

	public ComicId(int idComic, int serieIdserie) {
		this.idComic = idComic;
		this.serieIdserie = serieIdserie;
	}

	public int getIdComic() {
		return this.idComic;
	}

	public void setIdComic(int idComic) {
		this.idComic = idComic;
	}

	public int getSerieIdserie() {
		return this.serieIdserie;
	}

	public void setSerieIdserie(int serieIdserie) {
		this.serieIdserie = serieIdserie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComicId))
			return false;
		ComicId castOther = (ComicId) other;

		return (this.getIdComic() == castOther.getIdComic()) && (this.getSerieIdserie() == castOther.getSerieIdserie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdComic();
		result = 37 * result + this.getSerieIdserie();
		return result;
	}

}
