package orm;
// Generated 06-ene-2018 11:57:57 by Hibernate Tools 5.2.3.Final

/**
 * ComicHasSerieId generated by hbm2java
 */
public class ComicHasSerieId implements java.io.Serializable {

	private int comicIdComic;
	private int serieIdserie;

	public ComicHasSerieId() {
	}

	public ComicHasSerieId(int comicIdComic, int serieIdserie) {
		this.comicIdComic = comicIdComic;
		this.serieIdserie = serieIdserie;
	}

	public int getComicIdComic() {
		return this.comicIdComic;
	}

	public void setComicIdComic(int comicIdComic) {
		this.comicIdComic = comicIdComic;
	}

	public int getSerieIdserie() {
		return this.serieIdserie;
	}

	public void setSerieIdserie(int serieIdserie) {
		this.serieIdserie = serieIdserie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComicHasSerieId))
			return false;
		ComicHasSerieId castOther = (ComicHasSerieId) other;

		return (this.getComicIdComic() == castOther.getComicIdComic())
				&& (this.getSerieIdserie() == castOther.getSerieIdserie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getComicIdComic();
		result = 37 * result + this.getSerieIdserie();
		return result;
	}

}
