package orm;
// Generated 06-ene-2018 11:57:57 by Hibernate Tools 5.2.3.Final

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion implements java.io.Serializable {

	private PublicacionId id;
	private Comic comic;
	private Mediodepublicacion mediodepublicacion;
	private Boolean entregado;

	public Publicacion() {
	}

	public Publicacion(PublicacionId id, Comic comic, Mediodepublicacion mediodepublicacion) {
		this.id = id;
		this.comic = comic;
		this.mediodepublicacion = mediodepublicacion;
	}

	public Publicacion(PublicacionId id, Comic comic, Mediodepublicacion mediodepublicacion, Boolean entregado) {
		this.id = id;
		this.comic = comic;
		this.mediodepublicacion = mediodepublicacion;
		this.entregado = entregado;
	}

	public PublicacionId getId() {
		return this.id;
	}

	public void setId(PublicacionId id) {
		this.id = id;
	}

	public Comic getComic() {
		return this.comic;
	}

	public void setComic(Comic comic) {
		this.comic = comic;
	}

	public Mediodepublicacion getMediodepublicacion() {
		return this.mediodepublicacion;
	}

	public void setMediodepublicacion(Mediodepublicacion mediodepublicacion) {
		this.mediodepublicacion = mediodepublicacion;
	}

	public Boolean getEntregado() {
		return this.entregado;
	}

	public void setEntregado(Boolean entregado) {
		this.entregado = entregado;
	}
	
	public String toString() {
		return this.getId().getFecha().toString(); 
	}

}
