package orm;
// Generated 02-dic-2017 22:16:46 by Hibernate Tools 5.2.3.Final

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PublicacionId id;
	private Comic comic;
	private Mediodepublicacion mediodepublicacion;

	public Publicacion() {
	}

	public Publicacion(PublicacionId id, Comic comic, Mediodepublicacion mediodepublicacion) {
		this.id = id;
		this.comic = comic;
		this.mediodepublicacion = mediodepublicacion;
	}

	public PublicacionId getId() {
		return this.id;
	}

	public void setId(PublicacionId id) {
		this.id = id;
	}

	public Comic getComic() {
		return this.comic;
	}

	public void setComic(Comic comic) {
		this.comic = comic;
	}

	public Mediodepublicacion getMediodepublicacion() {
		return this.mediodepublicacion;
	}

	public void setMediodepublicacion(Mediodepublicacion mediodepublicacion) {
		this.mediodepublicacion = mediodepublicacion;
	}

}
