package orm;
// Generated 06-ene-2018 11:57:57 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Serie generated by hbm2java
 */
public class Serie implements java.io.Serializable {

	private int idserie;
	private String nombre;
	private String anotacionPrivada;
	private String genero;
	private Set<Mediodepublicacion> mediodepublicacions = new HashSet<Mediodepublicacion>(0);
	private Set<ComicHasSerie> comicHasSeries = new HashSet<ComicHasSerie>(0);

	public Serie() {
	}

	public Serie(int idserie, String nombre, String genero) {
		this.idserie = idserie;
		this.nombre = nombre;
		this.genero = genero;
	}

	public Serie(int idserie, String nombre, String anotacionPrivada, String genero,
			Set<Mediodepublicacion> mediodepublicacions, Set<ComicHasSerie> comicHasSeries) {
		this.idserie = idserie;
		this.nombre = nombre;
		this.anotacionPrivada = anotacionPrivada;
		this.genero = genero;
		this.mediodepublicacions = mediodepublicacions;
		this.comicHasSeries = comicHasSeries;
	}

	public String toString() {

		return " Serie:" + nombre + " Genero:" + genero;
	}

	public int getIdserie() {
		return this.idserie;
	}

	public void setIdserie(int idserie) {
		this.idserie = idserie;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getAnotacionPrivada() {
		return this.anotacionPrivada;
	}

	public void setAnotacionPrivada(String anotacionPrivada) {
		this.anotacionPrivada = anotacionPrivada;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public Set<Mediodepublicacion> getMediodepublicacions() {
		return this.mediodepublicacions;
	}

	public void setMediodepublicacions(Set<Mediodepublicacion> mediodepublicacions) {
		this.mediodepublicacions = mediodepublicacions;
	}

	public Set<ComicHasSerie> getComicHasSeries() {
		return this.comicHasSeries;
	}

	public void setComicHasSeries(Set<ComicHasSerie> comicHasSeries) {
		this.comicHasSeries = comicHasSeries;
	}

}
