// default package
// Generated 30-nov-2017 17:16:37 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Comic generated by hbm2java
 */
public class Comic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ComicId id;
	private Serie serie;
	private String nombre;
	private byte[] crossover;
	private Integer isbn;
	private byte[] foto;
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);

	public Comic() {
	}

	public Comic(ComicId id, Serie serie, String nombre) {
		this.id = id;
		this.serie = serie;
		this.nombre = nombre;
	}

	public Comic(ComicId id, Serie serie, String nombre, byte[] crossover, Integer isbn, byte[] foto,
			Set<Publicacion> publicacions) {
		this.id = id;
		this.serie = serie;
		this.nombre = nombre;
		this.crossover = crossover;
		this.isbn = isbn;
		this.foto = foto;
		this.publicacions = publicacions;
	}

	public ComicId getId() {
		return this.id;
	}

	public void setId(ComicId id) {
		this.id = id;
	}

	public Serie getSerie() {
		return this.serie;
	}

	public void setSerie(Serie serie) {
		this.serie = serie;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public byte[] getCrossover() {
		return this.crossover;
	}

	public void setCrossover(byte[] crossover) {
		this.crossover = crossover;
	}

	public Integer getIsbn() {
		return this.isbn;
	}

	public void setIsbn(Integer isbn) {
		this.isbn = isbn;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

}
