// default package
// Generated 30-nov-2017 16:13:38 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mediodepublicacion generated by hbm2java
 */
public class Mediodepublicacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nombre;
	private Set<Publicacion> publicacions = new HashSet<Publicacion>(0);
	private Set<Serie> series = new HashSet<Serie>(0);

	public Mediodepublicacion() {
	}

	public Mediodepublicacion(String nombre) {
		this.nombre = nombre;
	}

	public Mediodepublicacion(String nombre, Set<Publicacion> publicacions, Set<Serie> series) {
		this.nombre = nombre;
		this.publicacions = publicacions;
		this.series = series;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Publicacion> getPublicacions() {
		return this.publicacions;
	}

	public void setPublicacions(Set<Publicacion> publicacions) {
		this.publicacions = publicacions;
	}

	public Set<Serie> getSeries() {
		return this.series;
	}

	public void setSeries(Set<Serie> series) {
		this.series = series;
	}

}
